sudo: false
language: node_js
node_js:
  - "8"
script: testee test/*.html --browsers firefox --reporter Spec
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
cache:
  yarn: true
  directories:
    - node_modules
