sudo: false
language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - xvfb
script: testee test/*.html --browsers firefox --reporter Spec
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
cache:
  yarn: true
  directories:
    - node_modules
